version: "3.8"

services:
    app:
        image: mimidots/php8.0:1.2.0
        volumes:
            - $PWD:/var/www/html
        restart: on-failure
        ports:
            - "127.0.0.1:9000:9000"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - ppab

networks:
    ppab:
        name: ppab
        driver: bridge
