version: "3.8"

services:
  database:
    container_name: ${DB_HOST?err}
    image: mariadb:10.6.4
    restart: on-failure
    ports:
      - "${DB_PORT?err}"
    volumes:
      - ./storage/database/sqldb/:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: "${DB_DATABASE?err}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # for development use only
      MYSQL_PASSWORD: "${DB_PASSWORD?err}"
      MYSQL_USER: "${DB_USERNAME?err}"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ppab

  nginx:
    image: nginx:alpine
    restart: on-failure
    volumes:
      - $PWD:/var/www/html
      - $PWD/nginx-default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - ppab

  app:
    depends_on:
      - database
