<?php

namespace App\Utils;

abstract class PermissionUtils
{
    const  Permissions = [
        ['name' => 'organizationSettings.view', 'group' => 'organization',
            'description' => 'User can view organization settings'],
        ['name' => 'organizationSettings.edit', 'group' => 'organization',
            'description' => 'User can edit organization settings'],

        ['name' => 'role.view', 'group' => 'roles',
            'description' => 'User can view all roles'],
        ['name' => 'role.create', 'group' => 'roles',
            'description' => 'User can create role'],
        ['name' => 'role.edit', 'group' => 'roles',
            'description' => 'User can edit roles'],
        ['name' => 'role.delete', 'group' => 'roles',
            'description' => 'User can delete a role'],

        ['name' => 'user.view', 'group' => 'users',
            'description' => 'User can view all user accounts'],
        ['name' => 'user.create', 'group' => 'users',
            'description' => 'User can create a user account'],
        ['name' => 'user.edit', 'group' => 'users',
            'description' => 'User can edit a user account details'],
        ['name' => 'user.delete', 'group' => 'users',
            'description' => 'User can delete a user account'],

        ['name' => 'product.search', 'group' => 'products',
            'description' => 'User can search products'],
        ['name' => 'product.view', 'group' => 'products',
            'description' => 'User can view all products'],
        ['name' => 'product.create', 'group' => 'products',
            'description' => 'User can create a product'],
        ['name' => 'product.edit', 'group' => 'products',
            'description' => 'User can edit a product'],
        ['name' => 'product.delete', 'group' => 'products',
            'description' => 'User can delete a product'],

        ['name' => 'productItem.search', 'group' => 'products',
            'description' => 'User can search product items'],
        ['name' => 'productItem.view', 'group' => 'products',
            'description' => 'User can view all trackable product items'],
        ['name' => 'productItem.create', 'group' => 'products',
            'description' => 'User can add a trackable product item'],
        ['name' => 'productItem.edit', 'group' => 'products',
            'description' => 'User can edit trackable product item'],
        ['name' => 'productItem.delete', 'group' => 'products',
            'description' => 'User can delete trackable product item'],

        ['name' => 'tracking.view', 'group' => 'product tracking',
            'description' => 'User can view product item history logs '],
        ['name' => 'tracking.create', 'group' => 'product tracking',
            'description' => 'User can update product item location'],

        ['name' => 'customer.search', 'group' => 'customers',
            'description' => 'User can search customers'],
        ['name' => 'customer.view', 'group' => 'customers',
            'description' => 'User can view all customers'],
        ['name' => 'customer.create', 'group' => 'customers',
            'description' => 'User can create a customers'],
        ['name' => 'customer.edit', 'group' => 'customers',
            'description' => 'User can edit customers details'],
        ['name' => 'customer.delete', 'group' => 'customers',
            'description' => 'User can delete a customers'],

        ['name' => 'customerContract.view', 'group' => 'contracts',
            'description' => 'User can view all contracts'],
        ['name' => 'customerContract.create', 'group' => 'contracts',
            'description' => 'User can add a customer contract'],
        ['name' => 'customerContract.edit', 'group' => 'contracts',
            'description' => 'User can edit customer contracts'],
        ['name' => 'customerContract.delete', 'group' => 'contracts',
            'description' => 'User can delete any customer\' contract'],

        ['name' => 'worksheet.search', 'group' => 'worksheets',
            'description' => 'User can search worksheets'],
        ['name' => 'worksheet.view', 'group' => 'worksheets',
            'description' => 'User can view all worksheets (report)'],
        ['name' => 'worksheet.create', 'group' => 'worksheets',
            'description' => 'User can create a worksheet'],
        ['name' => 'worksheet.delete', 'group' => 'worksheets',
            'description' => 'User can delete any worksheets'],

        ['name' => 'stockBalance.view', 'group' => 'stock balances',
            'description' => 'User can view all stock balances'],
        ['name' => 'stockBalance.edit', 'group' => 'stock balances',
            'description' => 'User can adjust stock balances'],

        ['name' => 'receivingReport.view', 'group' => 'receiving report',
            'description' => 'User can view all RGA and GRN documents'],
        ['name' => 'receivingReport.approve', 'group' => 'receiving report',
            'description' => 'User can approve RGA and GRN documents'],

        ['name' => 'inspectionReport.view', 'group' => 'product inspection',
            'description' => 'User can view all created inspection reports'],
        ['name' => 'inspectionReport.create', 'group' => 'product inspection',
            'description' => 'User can inspect products'],

        ['name' => 'productCheckIn.create', 'group' => 'product checkin',
            'description' => 'User can receive/checkIn purchased and standby reminder products'],

        ['name' => 'purchaseOrder.search', 'group' => 'purchase orders',
            'description' => 'User can search purchase orders'],
        ['name' => 'purchaseOrder.view', 'group' => 'purchase orders',
            'description' => 'User can view all purchase orders'],
        ['name' => 'purchaseOrder.create', 'group' => 'purchase orders',
            'description' => 'User can create a purchase order'],
        ['name' => 'purchaseOrder.delete', 'group' => 'purchase orders',
            'description' => 'User can delete any purchase order'],

        ['name' => 'rfq.search', 'group' => 'RFQ\'s',
            'description' => 'User can search RFQ\'s'],
        ['name' => 'rfq.view', 'group' => 'RFQ\'s',
            'description' => 'User can view all RFQ\'s'],
        ['name' => 'rfq.create', 'group' => 'RFQ\'s',
            'description' => 'User can create an RFQ'],
        ['name' => 'rfq.delete', 'group' => 'RFQ\'s',
            'description' => 'User can delete any RFQ'],

        ['name' => 'purchaseRequest.search', 'group' => 'purchase requests',
            'description' => 'User can search purchase requests'],
        ['name' => 'purchaseRequest.create', 'group' => 'purchase requests',
            'description' => 'User can create a purchase request'],
        ['name' => 'purchaseRequest.check', 'group' => 'purchase requests',
            'description' => 'User can check/verify purchase requests'],
        ['name' => 'purchaseRequest.approve', 'group' => 'purchase requests',
            'description' => 'User can approve purchase requests'],

        ['name' => 'materialRequisition.create', 'group' => 'material requisition',
            'description' => 'User can create a material requisition request'],
        ['name' => 'materialRequisition.verify', 'group' => 'material requisition',
            'description' => 'User can verify material requisition form request'],
        ['name' => 'materialRequisition.approve', 'group' => 'material requisition',
            'description' => 'User can approve material requisition from request'],

        ['name' => 'checkout.create', 'group' => 'checkout',
            'description' => 'User can issue products on MRN approval'],
        ['name' => 'checkout.view', 'group' => 'checkout',
            'description' => 'User can view all checkouts (report)'],
    ];


}
